// Generated by vajram-lang-rust-compiler from helloWorld.vajram
#![allow(unused)]
use crate::vajram_rt::{Arena, Errable, VajramError};
use futures::future::FutureExt;
use std::rc::Rc;

pub mod hello_world {
    use super::*;

    #[derive(Debug, Clone)]
    pub struct HelloWorldInputs {}

    pub struct HelloWorld_Injections {
        pub writer: Rc<dyn crate::vajram_rt::Provider<dyn crate::vajram_rt::ConsoleWriter>>,
    }
    impl HelloWorld_Injections {
        fn new<I: crate::vajram_rt::Injector + 'static>(context: &crate::vajram_rt::AppContext<I>) -> Rc<Self> {
            Rc::new(Self {
                writer: context.injector().get_provider(crate::vajram_rt::InjectionKey::new("lang.process.ConsoleWriter", &[]), context),
            })
        }
        fn instance<I: crate::vajram_rt::Injector + 'static>(context: &crate::vajram_rt::AppContext<I>) -> Rc<Self> {
            context.injection_instance("HelloWorld_Injections", || Self::new(context))
        }
    }

    pub fn call<'a, I: crate::vajram_rt::Injector + 'static>(inputs: Vec<HelloWorldInputs>, arena: &'a Arena, context: &crate::vajram_rt::AppContext<I>) -> Vec<&'a ()> {
        let deps = HelloWorld_Injections::instance(context);
        inputs.into_iter().map(|inputs| call_one(inputs, Rc::clone(&deps), arena, context)).collect()
    }

    fn call_one<'a, I: crate::vajram_rt::Injector + 'static>(inputs: HelloWorldInputs, deps: Rc<HelloWorld_Injections>, arena: &'a Arena, context: &crate::vajram_rt::AppContext<I>) -> &'a () {
        arena.alloc(deps.writer.get().println("Hello! World.".to_string()))
    }
}
