// Generated by vajram-lang-rust-compiler from computeAveragePrice.vajram
#![allow(unused)]
use crate::vajram_rt::{Arena, Errable, VajramError};
use std::rc::Rc;

pub mod compute_average_price {
    use super::*;

    #[derive(Debug, Clone)]
    pub struct ComputeAveragePriceInputs<'a> {
        pub collection: &'a ProductCollection,
    }

    pub async fn call<'a, I: crate::vajram_rt::Injector + 'static>(
        inputs: Vec<ComputeAveragePriceInputs<'a>>,
        arena: &'a Arena,
        context: &crate::vajram_rt::AppContext<I>,
    ) -> Result<Vec<&'a f64>, VajramError> {
        futures::future::try_join_all(
            inputs
                .into_iter()
                .map(|inputs| call_one(inputs, arena, context)),
        )
        .await?
    }

    async fn call_one<'a, I: crate::vajram_rt::Injector + 'static>(
        inputs: ComputeAveragePriceInputs<'a>,
        arena: &'a Arena,
        context: &crate::vajram_rt::AppContext<I>,
    ) -> Result<&'a f64, VajramError> {
        let productDetails_fut = async {
            crate::com::flipkart::krystal::vajram_lang::samples::products::get_product_details::get_product_details::call(inputs.collection.productIds().into_iter().map(|it| crate::com::flipkart::krystal::vajram_lang::samples::products::get_product_details::get_product_details::GetProductDetailsInputs { productId: arena.alloc(it) }).collect(), arena, context).await
        };
        let productDetails = productDetails_fut.await;
        arena.alloc(
            productDetails
                .values()
                .stream()
                .filter(it.valuePresent())
                .map(it.price())
                .mapToDouble()
                .average(),
        )
    }
}
