// Generated by vajram-lang-rust-compiler from getAvailableProductDetails.vajram
#![allow(unused)]
use crate::vajram_rt::{Arena, Errable, VajramError};
use std::rc::Rc;

pub mod get_available_product_details {
    use super::*;

    #[derive(Debug, Clone)]
    pub struct GetAvailableProductDetailsInputs<'a> {
        pub productId: &'a String,
    }

    pub async fn call<'a, I: crate::vajram_rt::Injector + 'static>(
        inputs: Vec<GetAvailableProductDetailsInputs<'a>>,
        arena: &'a Arena,
        context: &crate::vajram_rt::AppContext<I>,
    ) -> Result<Vec<&'a ProductDetails>, VajramError> {
        futures::future::try_join_all(
            inputs
                .into_iter()
                .map(|inputs| call_one(inputs, arena, context)),
        )
        .await?
    }

    async fn call_one<'a, I: crate::vajram_rt::Injector + 'static>(
        inputs: GetAvailableProductDetailsInputs<'a>,
        arena: &'a Arena,
        context: &crate::vajram_rt::AppContext<I>,
    ) -> Result<&'a ProductDetails, VajramError> {
        let isAvailable_fut = async {
            (crate::com::flipkart::krystal::vajram_lang::samples::products::is_product_available::is_product_available::call(vec![crate::com::flipkart::krystal::vajram_lang::samples::products::is_product_available::is_product_available::IsProductAvailableInputs { productId: inputs.productId }], arena, context).await).into_iter().next().expect("single-item Vajram batch")
        };
        let isAvailable = isAvailable_fut.await;
        // NOTE: ignoring `skipIf` clause - not modeled by this compiler yet
        return (crate::com::flipkart::krystal::vajram_lang::samples::products::get_product_details::get_product_details::call(vec![crate::com::flipkart::krystal::vajram_lang::samples::products::get_product_details::get_product_details::GetProductDetailsInputs { productId: inputs.productId }], arena, context).await).into_iter().next().expect("single-item Vajram batch").default(|it| { ProductDetails::new(inputs.productId) });
    }
}
