// Generated by vajram-lang-rust-compiler from getProductDetails.vajram
#![allow(unused)]
use crate::vajram_rt::{Arena, Errable, VajramError};
use std::rc::Rc;

pub mod get_product_details {
    use super::*;

    #[derive(Debug, Clone)]
    pub struct GetProductDetailsInputs<'a> {
        pub productId: &'a String,
    }

    pub struct GetProductDetails_Injections {
        pub productDB: Rc<dyn crate::vajram_rt::Provider<ProductDB>>,
    }
    impl GetProductDetails_Injections {
        fn new<I: crate::vajram_rt::Injector + 'static>(
            context: &crate::vajram_rt::AppContext<I>,
        ) -> Rc<Self> {
            Rc::new(Self {
                productDB: context.injector().get_provider(
                    crate::vajram_rt::InjectionKey::new(
                        "com.flipkart.krystal.vajram_lang.samples.products.ProductDB",
                        &[],
                    ),
                    context,
                ),
            })
        }
        fn instance<I: crate::vajram_rt::Injector + 'static>(
            context: &crate::vajram_rt::AppContext<I>,
        ) -> Rc<Self> {
            context.injection_instance("GetProductDetails_Injections", || Self::new(context))
        }
    }

    pub async fn call<'a, I: crate::vajram_rt::Injector + 'static>(
        inputs: Vec<GetProductDetailsInputs<'a>>,
        arena: &'a Arena,
        context: &crate::vajram_rt::AppContext<I>,
    ) -> Result<Vec<&'a ProductDetails>, VajramError> {
        let deps = GetProductDetails_Injections::instance(context);
        futures::future::try_join_all(
            inputs
                .into_iter()
                .map(|inputs| call_one(inputs, Rc::clone(&deps), arena, context)),
        )
        .await?
    }

    async fn call_one<'a, I: crate::vajram_rt::Injector + 'static>(
        inputs: GetProductDetailsInputs<'a>,
        deps: Rc<GetProductDetails_Injections>,
        arena: &'a Arena,
        context: &crate::vajram_rt::AppContext<I>,
    ) -> Result<&'a ProductDetails, VajramError> {
        let productIds = batch_key.batches().map(|it| it.productId()).toList();
        let productDetails = deps
            .productDB
            .get()
            .getProductDetails(productIds)
            .await
            .stream()
            .await
            .toMap(BatchKey::new(it.productId()), it);
        productDetails
    }
}
