// Generated by vajram-lang-rust-compiler from isProductAvailable.vajram
#![allow(unused)]
use crate::vajram_rt::{Arena, Errable, VajramError};
use std::rc::Rc;

pub mod is_product_available {
    use super::*;

    #[derive(Debug, Clone)]
    pub struct IsProductAvailableInputs<'a> {
        pub productId: &'a String,
    }

    pub struct IsProductAvailable_Injections {
        pub availabilityDB: Rc<dyn crate::vajram_rt::Provider<AvailabilityDB>>,
    }
    impl IsProductAvailable_Injections {
        fn new<I: crate::vajram_rt::Injector + 'static>(
            context: &crate::vajram_rt::AppContext<I>,
        ) -> Rc<Self> {
            Rc::new(Self {
                availabilityDB: context.injector().get_provider(
                    crate::vajram_rt::InjectionKey::new(
                        "com.flipkart.krystal.vajram_lang.samples.products.AvailabilityDB",
                        &[],
                    ),
                    context,
                ),
            })
        }
        fn instance<I: crate::vajram_rt::Injector + 'static>(
            context: &crate::vajram_rt::AppContext<I>,
        ) -> Rc<Self> {
            context.injection_instance("IsProductAvailable_Injections", || Self::new(context))
        }
    }

    pub async fn call<'a, I: crate::vajram_rt::Injector + 'static>(
        inputs: Vec<IsProductAvailableInputs<'a>>,
        arena: &'a Arena,
        context: &crate::vajram_rt::AppContext<I>,
    ) -> Result<Vec<&'a bool>, VajramError> {
        let deps = IsProductAvailable_Injections::instance(context);
        futures::future::try_join_all(
            inputs
                .into_iter()
                .map(|inputs| call_one(inputs, Rc::clone(&deps), arena, context)),
        )
        .await?
    }

    async fn call_one<'a, I: crate::vajram_rt::Injector + 'static>(
        inputs: IsProductAvailableInputs<'a>,
        deps: Rc<IsProductAvailable_Injections>,
        arena: &'a Arena,
        context: &crate::vajram_rt::AppContext<I>,
    ) -> Result<&'a bool, VajramError> {
        arena.alloc(deps.availabilityDB.get().isAvailable(inputs.productId))
    }
}
