// Generated by vajram-lang-rust-compiler from getFriendsOfUser.vajram
#![allow(unused)]
use crate::vajram_rt::{Arena, Errable, VajramError};
use std::rc::Rc;

pub mod get_friends_of_user {
    use super::*;

    #[derive(Debug, Clone)]
    pub struct GetFriendsOfUserInputs<'a> {
        pub userId: &'a String,
    }

    pub struct GetFriendsOfUser_Injections {
        pub svcClient: Rc<dyn crate::vajram_rt::Provider<FriendServiceClient>>,
    }
    impl GetFriendsOfUser_Injections {
        fn new<I: crate::vajram_rt::Injector + 'static>(
            context: &crate::vajram_rt::AppContext<I>,
        ) -> Rc<Self> {
            Rc::new(Self {
            svcClient: context.injector().get_provider(crate::vajram_rt::InjectionKey::new("com.flipkart.krystal.vajram_lang.samples.friendsservice.FriendServiceClient", &[]), context),
            })
        }
        fn instance<I: crate::vajram_rt::Injector + 'static>(
            context: &crate::vajram_rt::AppContext<I>,
        ) -> Rc<Self> {
            context.injection_instance("GetFriendsOfUser_Injections", || Self::new(context))
        }
    }

    pub async fn call<'a, I: crate::vajram_rt::Injector + 'static>(
        inputs: Vec<GetFriendsOfUserInputs<'a>>,
        arena: &'a Arena,
        context: &crate::vajram_rt::AppContext<I>,
    ) -> Vec<&'a std::collections::HashSet<String>> {
        let deps = GetFriendsOfUser_Injections::instance(context);
        futures::future::join_all(
            inputs
                .into_iter()
                .map(|inputs| call_one(inputs, Rc::clone(&deps), arena, context)),
        )
        .await
    }

    async fn call_one<'a, I: crate::vajram_rt::Injector + 'static>(
        inputs: GetFriendsOfUserInputs<'a>,
        deps: Rc<GetFriendsOfUser_Injections>,
        arena: &'a Arena,
        context: &crate::vajram_rt::AppContext<I>,
    ) -> &'a std::collections::HashSet<String> {
        arena.alloc(
            deps.svcClient
                .get()
                .getFriendsIds(FriendServiceRequest::new(
                    ModKey::new().stream().map(|it| it.userId()).toSet(),
                ))
                .await
                .results()
                .await
                .default(List.of())
                .await
                .stream()
                .await
                .toMap(|it| (ModKey::new(it.userId()), it.friendIds())),
        )
    }
}
