// Generated by vajram-lang-rust-compiler from getUserInfo.vajram
#![allow(unused)]
use crate::vajram_rt::{Arena, Errable, VajramError};
use futures::future::FutureExt;
use std::rc::Rc;

pub mod get_user_info {
    use super::*;

    #[derive(Debug, Clone)]
    pub struct GetUserInfoInputs<'i> {
        pub userId: &'i String,
    }

    pub struct GetUserInfo_Injections {
        pub svcClient: Rc<dyn crate::vajram_rt::Provider<UserServiceClient>>,
    }
    impl GetUserInfo_Injections {
        fn new<I: crate::vajram_rt::Injector + 'static>(context: &crate::vajram_rt::AppContext<I>) -> Rc<Self> {
            Rc::new(Self {
                svcClient: context
                    .injector()
                    .get_provider(crate::vajram_rt::InjectionKey::new("com.flipkart.userservice.models.UserServiceClient", &[]), context),
            })
        }
        fn instance<I: crate::vajram_rt::Injector + 'static>(context: &crate::vajram_rt::AppContext<I>) -> Rc<Self> {
            context.injection_instance("GetUserInfo_Injections", || Self::new(context))
        }
    }

    pub async fn call<'a, 'i, I: crate::vajram_rt::Injector + 'static>(inputs: Vec<GetUserInfoInputs<'i>>, arena: &'a Arena, context: &crate::vajram_rt::AppContext<I>) -> Vec<&'a UserInfo> {
        let deps = GetUserInfo_Injections::instance(context);
        futures::future::join_all(inputs.into_iter().map(|inputs| call_one(inputs, Rc::clone(&deps), arena, context))).await
    }

    async fn call_one<'a, 'i, I: crate::vajram_rt::Injector + 'static>(
        inputs: GetUserInfoInputs<'i>,
        deps: Rc<GetUserInfo_Injections>,
        arena: &'a Arena,
        context: &crate::vajram_rt::AppContext<I>,
    ) -> &'a UserInfo {
        let () = futures::join!();
        inputs.userId
    }
}
