// Generated by vajram-lang-rust-compiler from sayHelloToFriends.vajram
#![allow(unused)]
use crate::vajram_rt::{Arena, Errable, VajramError};
use futures::future::FutureExt;
use std::rc::Rc;

pub mod say_hello_to_friends {
    use super::*;

    #[derive(Debug, Clone)]
    pub struct SayHelloToFriendsInputs<'i> {
        pub userId: &'i String,
        pub numberOfFriends: &'i Result<i64, VajramError>,
    }

    pub async fn call<'a, 'i, I: crate::vajram_rt::Injector + 'static>(inputs: Vec<SayHelloToFriendsInputs<'i>>, arena: &'a Arena, context: &crate::vajram_rt::AppContext<I>) -> Vec<&'a String> {
        futures::future::join_all(inputs.into_iter().map(|inputs| call_one(inputs, arena, context))).await
    }

    async fn call_one<'a, 'i, I: crate::vajram_rt::Injector + 'static>(inputs: SayHelloToFriendsInputs<'i>, arena: &'a Arena, context: &crate::vajram_rt::AppContext<I>) -> &'a String {
        let userInfo_fut = async move {
            (crate::com::flipkart::krystal::vajram_lang::samples::friends::get_user_info::get_user_info::call(
                vec![crate::com::flipkart::krystal::vajram_lang::samples::friends::get_user_info::get_user_info::GetUserInfoInputs { userId: inputs.userId }],
                arena,
                context,
            )
            .await)
                .into_iter()
                .next()
                .expect("single-item Vajram batch")
        }
        .boxed_local()
        .shared();
        let friendsInfos_fut = async move {
            crate::com::flipkart::krystal::vajram_lang::samples::friends::get_user_info::get_user_info::call(
                IntStream
                    .range(0, inputs.numberOfFriends.default(2))
                    .mapToObj(i, getFriendId(i))
                    .into_iter()
                    .map(|it| crate::com::flipkart::krystal::vajram_lang::samples::friends::get_user_info::get_user_info::GetUserInfoInputs { userId: arena.alloc(it) })
                    .collect(),
                arena,
                context,
            )
            .await
        }
        .boxed_local()
        .shared();
        let (userInfo, friendsInfos) = futures::join!(userInfo_fut.clone(), friendsInfos_fut.clone());
        arena.alloc(
            "Hello Friends of %s ! %s"
                .to_string()
                .formatted(userInfo.name(), friendInfos.responses().filterPresent().map(|it| it.userName()).collect(joining(", ".to_string()))),
        )
    }
}
