package com.flipkart.krystal.vajram.lang.rust.codegen;

import com.flipkart.krystal.vajram.lang.rust.ast.Completion;
import com.flipkart.krystal.vajram.lang.rust.ast.ComputedFacet;
import com.flipkart.krystal.vajram.lang.rust.ast.DepInputResolver;
import com.flipkart.krystal.vajram.lang.rust.ast.Dependency;
import com.flipkart.krystal.vajram.lang.rust.ast.DependencyInvocation;
import com.flipkart.krystal.vajram.lang.rust.ast.Expr;
import com.flipkart.krystal.vajram.lang.rust.ast.Field;
import com.flipkart.krystal.vajram.lang.rust.ast.InjectionDecl;
import com.flipkart.krystal.vajram.lang.rust.ast.InputDecl;
import com.flipkart.krystal.vajram.lang.rust.ast.LogicBlock;
import com.flipkart.krystal.vajram.lang.rust.ast.OutputBlock;
import com.flipkart.krystal.vajram.lang.rust.ast.Statement;
import com.flipkart.krystal.vajram.lang.rust.ast.VajramDef;
import com.flipkart.krystal.vajram.lang.rust.ast.VajramFile;
import com.flipkart.krystal.vajram.lang.rust.cli.RustCompilerMain.Target;
import com.flipkart.krystal.vajram.lang.rust.resolve.SymbolTable;
import com.flipkart.krystal.vajram.lang.rust.system.SystemVajram;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.stream.Collectors;
import org.jspecify.annotations.Nullable;

/**
 * Emits one Rust source module per Vajram source file. Each Vajram has an inputs struct, an
 * optional deps (injections) struct, and a {@code pub async fn call(Vec<...>)} entry point.
 * Dependency invocations always call other generated modules with a batch of input objects.
 *
 * <p><b>Memory model:</b> every Vajram call is handed an output arena ({@code arena: &'a
 * vajram_rt::Arena}) by its caller. A facet (field or dependency) without the {@code `local}
 * annotation is allocated into that same arena, so it survives past this Vajram's own return - a
 * borrowed {@code &'a T}, cascading zero-copy all the way up a call chain until something is
 * finally consumed without escaping further. A {@code `local}-annotated facet is a plain owned Rust
 * value instead: no arena, no refcounting, just freed by ordinary scope/drop when {@code call_one}
 * returns. DI singletons ({@code AppContext}/{@code Injector}/{@code Provider}) stay {@code
 * Rc}-based throughout - they are process/request-scoped, not per-call memory.
 */
public final class RustEmitter {

  private final SymbolTable symbolTable;
  private final Target target;
  private VajramFile currentFile;

  public RustEmitter(SymbolTable symbolTable) {
    this(symbolTable, Target.NATIVE);
  }

  public RustEmitter(SymbolTable symbolTable, Target target) {
    this.symbolTable = symbolTable;
    this.target = target;
  }

  public String emit(List<VajramFile> files) {
    RustWriter w = new RustWriter();
    w.line(
        "// Generated by vajram-lang-rust-compiler from "
            + files.get(0).sourcePath().getFileName());
    w.line("#![allow(unused)]");
    w.line("use crate::vajram_rt::{Arena, Errable, VajramError};");
    w.line("use futures::future::FutureExt;");
    w.line("use std::rc::Rc;");
    for (VajramFile file : files) {
      w.blank();
      w.openBlock("pub mod " + Naming.toSnakeCase(file.vajram().name()));
      w.line("use super::*;");
      w.blank();
      emit(file, w);
      w.closeBlock();
    }
    return w.toString();
  }

  private void emit(VajramFile file, RustWriter w) {
    currentFile = file;
    VajramDef vajram = file.vajram();
    String typeName = Naming.capitalize(vajram.name());
    Set<String> inputNames =
        vajram.inputs().stream().map(InputDecl::name).collect(Collectors.toSet());
    Set<String> injectionNames =
        vajram.injections().stream().map(InjectionDecl::name).collect(Collectors.toSet());
    Map<String, String> boundaryTypeNames = new HashMap<>();
    vajram.inputs().forEach(input -> boundaryTypeNames.put(input.name(), input.type().name()));
    vajram
        .injections()
        .forEach(injection -> boundaryTypeNames.put(injection.name(), injection.type().name()));
    Set<String> fieldNames =
        vajram.computedFacets().stream()
            .filter(Field.class::isInstance)
            .map(Field.class::cast)
            .map(Field::name)
            .collect(Collectors.toSet());
    Set<String> dependencyNames =
        vajram.computedFacets().stream()
            .filter(Dependency.class::isInstance)
            .map(Dependency.class::cast)
            .map(Dependency::name)
            .collect(Collectors.toSet());
    Set<String> facetNames = new LinkedHashSet<>(fieldNames);
    facetNames.addAll(dependencyNames);
    Set<String> localFacetNames =
        vajram.computedFacets().stream()
            .filter(RustEmitter::isLocal)
            .map(RustEmitter::facetName)
            .collect(Collectors.toSet());
    ExprEmitter exprs =
        new ExprEmitter(inputNames, injectionNames, boundaryTypeNames, localFacetNames);

    boolean inputsHaveLifetime = !vajram.inputs().isEmpty();
    emitInputsStruct(w, vajram, typeName, inputsHaveLifetime);
    boolean hasInjections = !vajram.injections().isEmpty();
    if (hasInjections) {
      emitDepsStruct(w, vajram, typeName);
    }

    Completion completion = symbolTable.completionOf(file);
    String inputsTypeRef = typeName + "Inputs" + (inputsHaveLifetime ? "<'i>" : "");
    // `'i` (Inputs struct fields) is kept independent of `'a` (this call's own arena/output
    // lifetime): a `local` facet's intermediate dependency calls borrow from short-lived scratch
    // arenas for their inputs, which must not force this call's own (possibly caller-chosen,
    // longer-lived) `'a` to shrink to match.
    String lifetimeParams = "'a" + (inputsHaveLifetime ? ", 'i" : "");
    String returnType = TypeMapper.toRustReturnType(vajram.outputType());
    String batchReturnType =
        vajram.outputType().errable()
            ? "Result<Vec<"
                + TypeMapper.toRustReturnType(
                    new com.flipkart.krystal.vajram.lang.rust.ast.TypeRef(
                        vajram.outputType().name(),
                        vajram.outputType().typeArgs(),
                        vajram.outputType().grouperType(),
                        false,
                        vajram.outputType().soon()))
                + ">, VajramError>"
            : "Vec<" + returnType + ">";
    String signature =
        "pub "
            + (completion.isAsync() ? "async " : "")
            + "fn call<"
            + lifetimeParams
            + ", I: crate::vajram_rt::Injector + 'static>(inputs: Vec<"
            + inputsTypeRef
            + ">"
            + ", arena: &'a Arena"
            + ", context: &crate::vajram_rt::AppContext<I>"
            + ") -> "
            + batchReturnType;
    w.openBlock(signature);
    if (hasInjections) {
      w.line("let deps = " + typeName + "_Injections::instance(context);");
    }
    String perInputCall =
        "call_one(inputs" + (hasInjections ? ", Rc::clone(&deps)" : "") + ", arena, context)";
    if (completion.isAsync()) {
      String joiner = vajram.outputType().errable() ? "try_join_all" : "join_all";
      w.line(
          "futures::future::"
              + joiner
              + "(inputs.into_iter().map(|inputs| "
              + perInputCall
              + ")).await"
              + (vajram.outputType().errable() ? "?" : ""));
    } else {
      w.line(
          "inputs.into_iter().map(|inputs| "
              + perInputCall
              + ").collect"
              + (vajram.outputType().errable() ? "::<Result<Vec<_>, _>>()" : "()"));
    }
    w.closeBlock();
    w.blank();
    String singleSignature =
        ""
            + (completion.isAsync() ? "async " : "")
            + "fn call_one<"
            + lifetimeParams
            + ", I: crate::vajram_rt::Injector + 'static>(inputs: "
            + inputsTypeRef
            + (hasInjections ? ", deps: Rc<" + typeName + "_Injections>" : "")
            + ", arena: &'a Arena"
            + ", context: &crate::vajram_rt::AppContext<I>"
            + ") -> "
            + returnType;
    w.openBlock(singleSignature);
    emitBody(w, vajram, exprs, completion, hasInjections, facetNames, localFacetNames);
    w.closeBlock();
  }

  private static boolean isLocal(ComputedFacet facet) {
    if (facet instanceof Field field) {
      return field.annotations().contains("local");
    } else if (facet instanceof Dependency dependency) {
      return dependency.annotations().contains("local");
    }
    throw new IllegalStateException("Unhandled computed facet kind: " + facet.getClass());
  }

  private static String facetName(ComputedFacet facet) {
    if (facet instanceof Field field) {
      return field.name();
    } else if (facet instanceof Dependency dependency) {
      return dependency.name();
    }
    throw new IllegalStateException("Unhandled computed facet kind: " + facet.getClass());
  }

  private void emitBody(
      RustWriter w,
      VajramDef vajram,
      ExprEmitter exprs,
      Completion completion,
      boolean hasDeps,
      Set<String> facetNames,
      Set<String> localFacetNames) {
    List<ComputedFacet> facets = vajram.computedFacets();
    // Every `local` dependency invocation needs some arena to hand the callee as its own output
    // arena (the callee always requires one), even though the result is discarded/owned rather
    // than escaping this call. One arena, declared once here and shared by every `local`
    // dependency in this Vajram, is enough - it (and everything bump-allocated into it) is freed
    // by ordinary drop when `call_one` returns, same as N separate scratch arenas would be.
    boolean hasLocalDependencies =
        facets.stream()
            .anyMatch(
                facet -> facet instanceof Dependency && localFacetNames.contains(facetName(facet)));
    if (hasLocalDependencies) {
      w.line("let __locals = Arena::new();");
    }
    if (completion.isAsync()) {
      emitAsyncFacetsGraph(
          w, facets, exprs, hasDeps, completion, facetNames, localFacetNames, hasLocalDependencies);
    } else {
      for (ComputedFacet facet : facets) {
        boolean local = localFacetNames.contains(facetName(facet));
        if (facet instanceof Field field) {
          w.append(emitSyncField(field, exprs, local));
        } else if (facet instanceof Dependency dependency) {
          w.append(emitSyncDependency(dependency, hasDeps, completion, exprs, facetNames, local));
        }
      }
    }
    w.append(emitOutputBlock(vajram.outputBlock(), hasDeps, completion, exprs, facetNames));
  }

  private String emitSyncField(Field field, ExprEmitter exprs, boolean local) {
    String value = exprs.emit(field.value());
    return "let " + field.name() + " = " + (local ? value : "arena.alloc(" + value + ")") + ";";
  }

  private String emitSyncDependency(
      Dependency dependency,
      boolean hasDeps,
      Completion completion,
      ExprEmitter exprs,
      Set<String> facetNames,
      boolean local) {
    StringBuilder sb = new StringBuilder();
    String targetArena = local ? "(&__locals)" : "arena";
    sb.append("let ")
        .append(dependency.name())
        .append(" = ")
        .append(
            emitInvocationCall(
                dependency.invocation(),
                dependency.fanout(),
                completion,
                exprs,
                facetNames,
                targetArena))
        .append(";");
    return sb.toString();
  }

  /**
   * Async Vajrams run every facet as a not-detached future (no spawning - detached tasks would need
   * {@code 'static} data, which is incompatible with borrowing this call's arena). Each facet is
   * wrapped as a {@code futures::future::Shared} future (memoizing, poll-anywhere, requires {@code
   * Output: Clone} - already guaranteed by this system's {@code Errable<T: Clone>} contract). A
   * facet's own async block clones+awaits only the {@code Shared} futures of the facets it actually
   * references (per {@link #collectFacetRefs}) - never every other facet that merely happens to be
   * declared nearby. All facets are then driven concurrently with a single flat {@code
   * futures::join!} over every facet in this call, so independent facets still start immediately,
   * and each facet blocks on exactly - and only - the futures it needs, regardless of how many
   * other unrelated facets exist alongside it.
   *
   * <p>The source list is already declared in a valid dependency order (a facet can only reference
   * facets declared earlier - the same assumption the sync path above relies on), so facets are
   * emitted in that same original order; no separate topological sort is required.
   */
  private void emitAsyncFacetsGraph(
      RustWriter w,
      List<ComputedFacet> facets,
      ExprEmitter exprs,
      boolean hasDeps,
      Completion completion,
      Set<String> facetNames,
      Set<String> localFacetNames,
      boolean hasLocalDependencies) {
    if (hasLocalDependencies) {
      // `async move` blocks capture every free variable they reference *by move*. Referencing
      // `__locals` (the Arena itself) by name inside a block would move the whole arena in,
      // leaving the returned `&T` dangling once that (now block-owned) arena drops with the
      // future. Take the reference once, outside every block, instead - a `&Arena` is `Copy`, so
      // each `async move` block below only captures a pointer, leaving the arena itself owned by
      // this outer `call_one` frame for the whole of its body.
      w.line("let __locals_ref = &__locals;");
    }
    Map<String, Set<String>> refs = new LinkedHashMap<>();
    for (ComputedFacet facet : facets) {
      Set<String> referenced = new LinkedHashSet<>();
      collectFacetRefs(facet, facetNames, referenced);
      referenced.remove(facetName(facet));
      refs.put(facetName(facet), referenced);
    }
    List<String> allNames = new ArrayList<>();
    for (ComputedFacet facet : facets) {
      String name = facetName(facet);
      boolean local = localFacetNames.contains(name);
      String futureBody;
      String targetArena = "arena";
      // `async move` captures every free variable it references *by move*. For a dependency's
      // `Shared` future, cloning it *inside* the block (`dep_fut.clone().await`) would move the
      // original `dep_fut` itself into this block, leaving it inaccessible to the final flat
      // `join!` (and to any other sibling that also depends on it) - a "borrow of moved value"
      // error. So the clone must happen *outside*, as its own statement, and only the (fresh,
      // single-use) clone gets moved in.
      StringBuilder depAwaits = new StringBuilder();
      for (String dep : refs.getOrDefault(name, Set.of())) {
        String cloneVar = "_" + name + "_needs_" + dep;
        w.line("let " + cloneVar + " = " + dep + "_fut.clone();");
        depAwaits.append("let ").append(dep).append(" = ").append(cloneVar).append(".await; ");
      }
      if (facet instanceof Field field) {
        String value = exprs.emit(field.value());
        // `Arena::alloc` (bumpalo) returns `&mut T`; `Shared` requires `Output: Clone`, which
        // `&mut T` never is (only `&T` is). Reborrow immutably right away so this facet's
        // `Shared` future has a `&T` output, matching every other (dependency-call-derived)
        // facet - a real vajram callee's own return type already forces this same coercion at
        // its `call_one` boundary, so this only changes behavior for plain computed fields.
        futureBody = local ? value : "&*arena.alloc(" + value + ")";
      } else {
        Dependency dependency = (Dependency) facet;
        if (local) {
          targetArena = "__locals_ref";
        }
        futureBody =
            emitInvocationCall(
                dependency.invocation(),
                dependency.fanout(),
                completion,
                exprs,
                facetNames,
                targetArena);
      }
      w.line(
          "let "
              + name
              + "_fut = async move { "
              + depAwaits
              + futureBody
              + " }.boxed_local().shared();");
      allNames.add(name);
    }
    if (allNames.size() == 1) {
      String name = allNames.get(0);
      w.line("let " + name + " = " + name + "_fut.clone().await;");
    } else {
      String lhs = String.join(", ", allNames);
      String rhs = allNames.stream().map(n -> n + "_fut.clone()").collect(Collectors.joining(", "));
      w.line("let (" + lhs + ") = futures::join!(" + rhs + ");");
    }
  }

  /**
   * Collects every referenced facet name (field or dependency) reachable from a facet's own body.
   */
  private void collectFacetRefs(ComputedFacet facet, Set<String> facetNames, Set<String> out) {
    if (facet instanceof Field field) {
      collectVarNames(field.value(), facetNames, out);
    } else if (facet instanceof Dependency dependency) {
      for (DepInputResolver resolver : dependency.invocation().resolvers()) {
        if (resolver instanceof DepInputResolver.Stat stat) {
          stat.values().forEach(value -> collectVarNames(value, facetNames, out));
        } else if (resolver instanceof DepInputResolver.Func func) {
          collectVarNames(func.body(), facetNames, out);
        }
      }
    }
  }

  private void collectVarNames(LogicBlock block, Set<String> facetNames, Set<String> out) {
    block.statements().forEach(statement -> collectVarNames(statement, facetNames, out));
    if (block.yield() != null) {
      block.yield().values().forEach(value -> collectVarNames(value, facetNames, out));
    }
  }

  private void collectVarNames(Statement statement, Set<String> facetNames, Set<String> out) {
    if (statement instanceof Statement.Assign a) {
      collectVarNames(a.value(), facetNames, out);
    } else if (statement instanceof Statement.Expression e) {
      collectVarNames(e.value(), facetNames, out);
    } else if (statement instanceof Statement.Throw t) {
      collectVarNames(t.value(), facetNames, out);
    }
  }

  private void collectVarNames(Expr expr, Set<String> facetNames, Set<String> out) {
    if (expr instanceof Expr.VarUse v) {
      if (facetNames.contains(v.name())) {
        out.add(v.name());
      }
    } else if (expr instanceof Expr.Array a) {
      a.elements().forEach(e -> collectVarNames(e, facetNames, out));
    } else if (expr instanceof Expr.Not n) {
      collectVarNames(n.operand(), facetNames, out);
    } else if (expr instanceof Expr.BinaryOp b) {
      collectVarNames(b.left(), facetNames, out);
      collectVarNames(b.right(), facetNames, out);
    } else if (expr instanceof Expr.MethodRef m) {
      collectVarNames(m.target(), facetNames, out);
    } else if (expr instanceof Expr.MemberAccess m) {
      collectVarNames(m.target(), facetNames, out);
    } else if (expr instanceof Expr.ChainedCall c) {
      collectVarNames(c.target(), facetNames, out);
      collectVarNames(c.call(), facetNames, out);
    } else if (expr instanceof Expr.Call c) {
      c.args().forEach(arg -> collectVarNames(arg, facetNames, out));
      if (c.lambda() != null) {
        collectVarNames(c.lambda(), facetNames, out);
      }
    } else if (expr instanceof Expr.FuncChain fc) {
      fc.calls().forEach(call -> collectVarNames(call, facetNames, out));
    }
    // VarUse (handled above), StringLiteral, IntLiteral, BoolLiteral, GrouperRef: no children.
  }

  private void collectVarNames(Expr.LambdaBody body, Set<String> facetNames, Set<String> out) {
    body.statements().forEach(statement -> collectVarNames(statement, facetNames, out));
    if (body.yield() != null) {
      body.yield().values().forEach(value -> collectVarNames(value, facetNames, out));
    }
  }

  private void emitInputsStruct(
      RustWriter w, VajramDef vajram, String typeName, boolean hasLifetime) {
    w.openBlock(
        "#[derive(Debug, Clone)]\npub struct " + typeName + "Inputs" + (hasLifetime ? "<'i>" : ""));
    for (InputDecl input : vajram.inputs()) {
      w.line("pub " + input.name() + ": " + TypeMapper.toRustOwnedType(input.type(), "i") + ",");
    }
    w.closeBlock();
    w.blank();
  }

  private void emitDepsStruct(RustWriter w, VajramDef vajram, String typeName) {
    String injectionsType = typeName + "_Injections";
    w.openBlock("pub struct " + injectionsType);
    for (InjectionDecl injection : vajram.injections()) {
      w.line(
          "pub "
              + injection.name()
              + ": Rc<dyn crate::vajram_rt::Provider<"
              + TypeMapper.toRustValueType(injection.type())
              + ">>,");
    }
    w.closeBlock();
    w.openBlock("impl " + injectionsType);
    w.openBlock(
        "fn new<I: crate::vajram_rt::Injector + 'static>(context: &crate::vajram_rt::AppContext<I>) -> Rc<Self>");
    w.line("Rc::new(Self {");
    for (InjectionDecl injection : vajram.injections()) {
      w.line(
          injection.name()
              + ": context.injector()."
              + "get_provider"
              + "(crate::vajram_rt::InjectionKey::new(\""
              + fullyQualifiedInjectionTypeName(injection)
              + "\", &["
              + injection.annotations().stream()
                  .map(annotation -> "\"" + annotation + "\"")
                  .collect(Collectors.joining(", "))
              + "]), context),");
    }
    w.line("})");
    w.closeBlock();
    w.openBlock(
        "fn instance<I: crate::vajram_rt::Injector + 'static>(context: &crate::vajram_rt::AppContext<I>) -> Rc<Self>");
    w.line("context.injection_instance(\"" + injectionsType + "\", || Self::new(context))");
    w.closeBlock();
    w.closeBlock();
    w.blank();
  }

  private String fullyQualifiedInjectionTypeName(InjectionDecl injection) {
    String typeName = injection.type().name();
    if (TypeMapper.isPrimitive(typeName)) {
      return typeName;
    }
    return currentFile.imports().stream()
        .filter(imported -> imported.vajramName().equals(typeName))
        .map(imported -> String.join(".", imported.sourceSegments()) + "." + typeName)
        .findFirst()
        .orElseGet(
            () ->
                "ConsoleWriter".equals(typeName)
                    ? "lang.process.ConsoleWriter"
                    : String.join(".", currentFile.packageSegments()) + "." + typeName);
  }

  private String emitOutputBlock(
      OutputBlock block,
      boolean hasDeps,
      Completion completion,
      ExprEmitter exprs,
      Set<String> facetNames) {
    if (block instanceof OutputBlock.Logic logic) {
      return exprs.emitOwnedBlockBody(logic.body().statements(), logic.body().yield());
    } else if (block instanceof OutputBlock.Delegate delegate) {
      return emitDelegate(delegate, hasDeps, completion, exprs, facetNames);
    }
    throw new IllegalStateException("Unhandled output block kind: " + block.getClass());
  }

  private String emitDelegate(
      OutputBlock.Delegate delegate,
      boolean hasDeps,
      Completion completion,
      ExprEmitter exprs,
      Set<String> facetNames) {
    DependencyInvocation invocation = delegate.invocation();
    StringBuilder sb = new StringBuilder();
    for (var block : invocation.extraAnnotatedBlocks()) {
      sb.append("// NOTE: ignoring `")
          .append(String.join(" ", block.annotations()))
          .append("` clause - not modeled by this compiler yet\n");
    }
    // The output block's own result always feeds this Vajram's return value, so it always
    // allocates directly into the received output arena, never a throwaway scratch.
    String call = emitInvocationCall(invocation, false, completion, exprs, facetNames, "arena");
    if (invocation.errableFallback() != null) {
      call = call + "." + exprs.emit(invocation.errableFallback());
    }
    sb.append("return ").append(call).append(";");
    return sb.toString();
  }

  private String emitInvocationCall(
      DependencyInvocation invocation,
      boolean declaredFanout,
      Completion callerCompletion,
      ExprEmitter exprs,
      Set<String> facetNames,
      String targetArena) {
    VajramFile callee = symbolTable.lookup(invocation.vajramName());
    String calleeModule = calleeModule(callee, invocation.vajramName());
    String calleeType = Naming.capitalize(invocation.vajramName());
    boolean calleeErrable = isCalleeErrable(invocation.vajramName());
    String contextArg = ", context";
    String arenaArg = ", " + targetArena;

    var systemVajram = SystemVajram.lookup(invocation.vajramName(), currentFile.imports());
    if (systemVajram.isPresent()) {
      return switch (systemVajram.get()) {
        case READ_FILE_AS_STRING -> emitReadFileAsString(invocation, exprs, targetArena);
        case CONCAT_STRINGS -> emitConcatStrings(invocation, exprs, targetArena);
        case CALL_HTTP -> emitCallHttp(invocation, exprs, targetArena);
      };
    }

    DepInputResolver fannedResolver = findFanned(invocation, declaredFanout);
    if (fannedResolver == null) {
      List<String> fieldList = new ArrayList<>();
      for (DepInputResolver resolver : invocation.resolvers()) {
        fieldList.addAll(fieldAssignments(resolver, exprs, targetArena));
      }
      String fields = String.join(", ", fieldList);
      String call =
          calleeModule
              + "::call("
              + "vec!["
              + calleeModule
              + "::"
              + calleeType
              + "Inputs { "
              + fields
              + " }]"
              + arenaArg
              + contextArg
              + ")";
      return singleBatchResult(asyncInvocation(call, invocation.vajramName(), calleeErrable));
    }

    String fannedField =
        fannedResolver.targetInputs().isEmpty() ? "value" : fannedResolver.targetInputs().get(0);
    String fannedExpr = resolverValueTexts(fannedResolver, exprs).stream().findFirst().orElse("[]");
    if (fannedResolver instanceof DepInputResolver.Stat stat
        && stat.values().size() == 1
        && stat.values().get(0)
            instanceof com.flipkart.krystal.vajram.lang.rust.ast.Expr.VarUse varUse
        && facetNames.contains(varUse.name())) {
      fannedExpr += ".clone()";
    }
    List<String> otherFields = new ArrayList<>();
    for (DepInputResolver resolver : invocation.resolvers()) {
      if (resolver != fannedResolver) {
        otherFields.addAll(fieldAssignments(resolver, exprs, targetArena));
      }
    }
    String restFields = otherFields.isEmpty() ? "" : ", " + String.join(", ", otherFields);
    String fanoutCall =
        calleeModule
            + "::call("
            + fannedExpr
            + ".into_iter().map(|it| "
            + calleeModule
            + "::"
            + calleeType
            + "Inputs { "
            + fannedField
            + ": "
            + targetArena
            + ".alloc(it)"
            + restFields
            + " }).collect()"
            + arenaArg
            + contextArg
            + ")";
    return asyncInvocation(fanoutCall, invocation.vajramName(), calleeErrable);
  }

  private static String calleeModule(@Nullable VajramFile callee, String vajramName) {
    if (callee == null) {
      return Naming.toSnakeCase(vajramName);
    }
    String packagePath =
        callee.packageSegments().stream()
            .map(Naming::toSnakeCase)
            .collect(Collectors.joining("::"));
    return "crate::"
        + (packagePath.isEmpty() ? "" : packagePath + "::")
        + Naming.sourceModuleName(callee.sourcePath())
        + "::"
        + Naming.toSnakeCase(callee.vajram().name());
  }

  private String asyncInvocation(String call, String vajramName, boolean calleeErrable) {
    VajramFile callee = symbolTable.lookup(vajramName);
    if (callee == null || !symbolTable.completionOf(callee).isAsync()) {
      return call + (calleeErrable ? "?" : "");
    }
    return call + ".await";
  }

  private static String singleBatchResult(String call) {
    return "(" + call + ").into_iter().next().expect(\"single-item Vajram batch\")";
  }

  private String emitReadFileAsString(
      DependencyInvocation invocation, ExprEmitter exprs, String targetArena) {
    for (DepInputResolver resolver : invocation.resolvers()) {
      if (resolver instanceof DepInputResolver.Stat stat
          && stat.targetInputs().size() == 1
          && "path".equals(stat.targetInputs().get(0))
          && stat.values().size() == 1) {
        String path = exprs.emit(stat.values().get(0));
        // See the comment on the plain-Field case above: `.alloc()` returns `&mut T`, reborrow
        // immutably so this is `Clone`-able when wrapped in a `Shared` future.
        return "&*"
            + targetArena
            + ".alloc(tokio::fs::read_to_string("
            + path
            + ".as_str()"
            + ").await.expect(\"readFileAsString failed\"))";
      }
    }
    throw new IllegalArgumentException("readFileAsString requires exactly one path resolver");
  }

  private String emitCallHttp(
      DependencyInvocation invocation, ExprEmitter exprs, String targetArena) {
    for (DepInputResolver resolver : invocation.resolvers()) {
      if (resolver instanceof DepInputResolver.Stat stat
          && stat.targetInputs().size() == 1
          && "url".equals(stat.targetInputs().get(0))
          && stat.values().size() == 1) {
        String url = exprs.emit(stat.values().get(0)) + ".as_str()";
        String body =
            target == Target.WASM
                ? "crate::vajram_rt::fetch_text(" + url + ").await"
                // Some hosts (e.g. api.weather.gov's Akamai edge) reject requests with no
                // User-Agent header ("Access Denied"), unlike browsers which always send one.
                : "reqwest::Client::new().get("
                    + url
                    + ").header(reqwest::header::USER_AGENT, \"vajram-lang\")"
                    + ".send().await.expect(\"callHttp failed\").text().await.expect(\"callHttp failed\")";
        return "&*" + targetArena + ".alloc(" + body + ")";
      }
    }
    throw new IllegalArgumentException("callHttp requires exactly one url resolver");
  }

  private String emitConcatStrings(
      DependencyInvocation invocation, ExprEmitter exprs, String targetArena) {
    String strings = null;
    String separator = null;
    for (DepInputResolver resolver : invocation.resolvers()) {
      if (resolver instanceof DepInputResolver.Stat stat) {
        int count = Math.min(stat.targetInputs().size(), stat.values().size());
        for (int i = 0; i < count; i++) {
          if ("strings".equals(stat.targetInputs().get(i))) {
            strings = exprs.emit(stat.values().get(i));
          } else if ("separator".equals(stat.targetInputs().get(i))) {
            separator = exprs.emit(stat.values().get(i));
          }
        }
      }
    }
    if (strings == null || separator == null) {
      throw new IllegalArgumentException(
          "concatStrings requires exactly one strings resolver and one separator resolver");
    }
    return "&*"
        + targetArena
        + ".alloc("
        + strings
        + ".iter().map(|value| value.as_str()).collect::<Vec<_>>().join("
        + separator
        + ".as_str()))";
  }

  private @Nullable DepInputResolver findFanned(
      DependencyInvocation invocation, boolean declaredFanout) {
    for (DepInputResolver resolver : invocation.resolvers()) {
      if (resolver.fanout()) {
        return resolver;
      }
    }
    return (declaredFanout || invocation.fanout()) && !invocation.resolvers().isEmpty()
        ? invocation.resolvers().get(0)
        : null;
  }

  private List<String> fieldAssignments(
      DepInputResolver resolver, ExprEmitter exprs, String targetArena) {
    List<String> targets = resolver.targetInputs();
    List<String> values = resolverValueTexts(resolver, exprs);
    List<String> result = new ArrayList<>();
    int n = Math.min(targets.size(), values.size());
    for (int i = 0; i < n; i++) {
      result.add(
          targets.get(i) + ": " + ownedValue(values.get(i), resolver, i, exprs, targetArena));
    }
    return result;
  }

  private List<String> resolverValueTexts(DepInputResolver resolver, ExprEmitter exprs) {
    if (resolver instanceof DepInputResolver.Stat stat) {
      return stat.values().stream().map(exprs::emit).toList();
    } else if (resolver instanceof DepInputResolver.Func func) {
      return List.of(
          "{ " + exprs.emitBlockBody(func.body().statements(), func.body().yield()) + " }");
    }
    throw new IllegalStateException("Unhandled resolver kind: " + resolver.getClass());
  }

  /**
   * Homes a value that's about to cross into a callee's inputs. A bare reference to an input,
   * injection, or non-{@code `local} sibling facet is already a {@code &'a T} tied to (at least)
   * this call's own output arena, so it's a free `Copy` passthrough - safe to hand to a callee
   * expecting a shorter-lived scratch arena's lifetime too, by reference subtyping. Anything else
   * (a `local` facet's owned value, or a freshly computed expression) needs to be homed into
   * whichever arena backs this particular callee invocation.
   */
  private String ownedValue(
      String value, DepInputResolver resolver, int index, ExprEmitter exprs, String targetArena) {
    if (resolver instanceof DepInputResolver.Stat stat
        && stat.values().get(index)
            instanceof com.flipkart.krystal.vajram.lang.rust.ast.Expr.VarUse varUse
        && !exprs.isLocalFacetName(varUse.name())) {
      return value;
    }
    return targetArena + ".alloc(" + value + ")";
  }

  private boolean isCalleeErrable(String vajramName) {
    VajramFile callee = symbolTable.lookup(vajramName);
    return callee != null && callee.vajram().outputType().errable();
  }
}
